CATALOGUE_PAGINATION = 15
CATALOGUE_PAGINATION_ORPHANS = 5

WAREHOUSE_PAGINATION = 9
WAREHOUSE_PAGINATION_ORPHANS = 3

CIRCULATION_MAX_ACTIVE_IDS = 1
CIRCULATION_MAX_LENDINGS_PER_CUSTOMER = 1
CIRCULATION_MAX_LENDINGS_PER_CUSTOMERID = 1
CIRCULATION_LENDING_PAGINATION = 9
CIRCULATION_LENDING_PAGINATION_ORPHANS = 3
