# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-25 10:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0004_auto_20180218_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('board_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.BoardGameItem')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('desc', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='container',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.Warehouse'),
        ),
        migrations.AlterUniqueTogether(
            name='container',
            unique_together=set([('warehouse', 'board_game')]),
        ),
    ]
