# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-10 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgamecontainer',
            name='commodity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='catalogue.BoardGameCommodity'),
        ),
        migrations.AlterField(
            model_name='boardgamecontainer',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='warehouse.Warehouse'),
        ),
    ]
