# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-19 12:11
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_auto_20180515_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgamecontainer',
            name='total',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
