# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-11 20:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogueItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemLabel', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CodeLabelledItem',
            fields=[
                ('catalogueitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalogue.CatalogueItem')),
                ('codeLabel', models.CharField(choices=[('BAR', 'Barcode'), ('QR', 'QR code')], default='BAR', max_length=3)),
            ],
            bases=('catalogue.catalogueitem',),
        ),
        migrations.CreateModel(
            name='BoardGameItem',
            fields=[
                ('codelabelleditem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalogue.CodeLabelledItem')),
                ('bggURL', models.URLField(max_length=100)),
                ('basegame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extensions', to='catalogue.BoardGameItem')),
            ],
            bases=('catalogue.codelabelleditem',),
        ),
    ]
