# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-18 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgameitem',
            name='codeValue',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
