# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-11 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codelabelleditem',
            old_name='codeLabel',
            new_name='codeType',
        ),
        migrations.AddField(
            model_name='codelabelleditem',
            name='codeValue',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
