# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-18 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_auto_20180218_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgameitem',
            name='bggURL',
            field=models.URLField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='boardgameitem',
            name='codeValue',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='Etykieta kodu'),
        ),
    ]
