# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-11 21:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_auto_20180211_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgameitem',
            name='basegame',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extensions', to='catalogue.BoardGameItem'),
        ),
    ]
