# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-23 19:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_auto_20180218_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeType', models.CharField(choices=[('BAR', 'Barcode'), ('QR', 'QR code')], default='BAR', max_length=3)),
                ('codeValue', models.CharField(max_length=20, null=True, unique=True, verbose_name='Etykieta kodu')),
            ],
        ),
        migrations.RemoveField(
            model_name='boardgameitem',
            name='codeType',
        ),
        migrations.RemoveField(
            model_name='boardgameitem',
            name='codeValue',
        ),
        migrations.AddField(
            model_name='commodity',
            name='catalogueEntry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogue.BoardGameItem'),
        ),
    ]
