# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-23 20:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_auto_20180223_2057'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commodity',
            new_name='BoardGameCommodity',
        ),
    ]
