# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-24 09:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_auto_20180223_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardgameitem',
            name='basegame',
        ),
        migrations.AddField(
            model_name='boardgameitem',
            name='baseGameItem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basegameXXX', to='catalogue.BoardGameItem'),
        ),
        migrations.AlterField(
            model_name='boardgamecommodity',
            name='catalogueEntry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commodities', to='catalogue.BoardGameItem'),
        ),
    ]
