# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-24 10:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_auto_20180224_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgameitem',
            name='baseGameItem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basegame', to='catalogue.BoardGameItem'),
        ),
    ]
