# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-24 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0009_auto_20180224_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgamecommodity',
            name='frontImage',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='boardgamecommodity',
            name='sideImages',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='boardgamecommodity',
            name='topImage',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
