# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-24 12:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0010_auto_20180224_1334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardgamecommodity',
            old_name='sideImages',
            new_name='sideImage',
        ),
    ]
