# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-24 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0011_auto_20180224_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgamecommodity',
            name='catalogueEntry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commodities', to='catalogue.BoardGameItem'),
        ),
        migrations.AlterField(
            model_name='boardgamecommodity',
            name='frontImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='boardgamecommodity',
            name='sideImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='boardgamecommodity',
            name='topImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
