# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-24 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0013_auto_20180224_1450'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardgamecommodity',
            options={'verbose_name': 'Wydanie gry planszowej'},
        ),
        migrations.AlterField(
            model_name='boardgamecommodity',
            name='boxFrontImage',
            field=models.ImageField(blank=True, null=True, upload_to='bg/img/'),
        ),
        migrations.AlterField(
            model_name='boardgamecommodity',
            name='boxSideImage',
            field=models.ImageField(blank=True, null=True, upload_to='bg/img/'),
        ),
        migrations.AlterField(
            model_name='boardgamecommodity',
            name='boxTopImage',
            field=models.ImageField(blank=True, null=True, upload_to='bg/img/'),
        ),
    ]
