# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-25 18:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0014_auto_20180224_1752'),
        ('catalogue', '0006_delete_rentalclient'),
    ]

    operations = [
    ]
