# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-02 18:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0015_merge_20180225_1959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardgameitem',
            options={'ordering': ['itemLabel']},
        ),
    ]
