# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-02 18:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0016_auto_20180228_1755'),
        ('catalogue', '0016_auto_20180226_2016'),
    ]

    operations = [
    ]
