# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-03 20:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0017_merge_20180302_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgamecommodity',
            name='catalogueEntry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commodities', to='catalogue.BoardGameItem'),
        ),
    ]
