# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-03 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0019_auto_20180303_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgamecommodity',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Informacje o wydaniu'),
        ),
    ]
