# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-04 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0020_boardgamecommodity_description'),
        ('catalogue', '0016_auto_20180302_1949'),
    ]

    operations = [
    ]
