# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-07 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0021_merge_20180304_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgameitem',
            name='bggURL',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
