# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-13 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0022_auto_20180408_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgameitem',
            name='boargGameImage',
            field=models.ImageField(blank=True, null=True, upload_to='bg/img/'),
        ),
    ]
