# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-13 17:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0023_boardgameitem_boarggameimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardgameitem',
            old_name='boargGameImage',
            new_name='itemImage',
        ),
    ]
