# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-24 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0025_auto_20180413_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgamecommodity',
            name='boxFrontImage',
            field=models.ImageField(blank=True, null=True, upload_to='catalogue/bg/%M'),
        ),
        migrations.AlterField(
            model_name='boardgamecommodity',
            name='boxSideImage',
            field=models.ImageField(blank=True, null=True, upload_to='catalogue/bg/%M'),
        ),
        migrations.AlterField(
            model_name='boardgamecommodity',
            name='boxTopImage',
            field=models.ImageField(blank=True, null=True, upload_to='catalogue/bg/%M'),
        ),
    ]
