# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-24 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RentalClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificationCode', models.IntegerField(max_length=10, unique=True)),
                ('initials', models.CharField(max_length=10)),
            ],
        ),
    ]
