# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-25 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalclient',
            name='identificationCode',
            field=models.IntegerField(unique=True),
        ),
    ]
