# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-04 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
        ('circulation', '0004_auto_20180225_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientHasBoardGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circulation.RentalClient')),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.BoardGameContainer')),
            ],
        ),
    ]
