# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-03 07:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0004_auto_20180225_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientID',
            fields=[
                ('IDs', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('rentalClient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='circulation.RentalClient')),
            ],
        ),
    ]
