# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-03 07:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0005_clientid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientid',
            old_name='IDs',
            new_name='ID',
        ),
    ]
