# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-03 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0006_auto_20180303_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientid',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
