# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-04 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0007_clientid_active'),
        ('circulation', '0005_clienthasboardgame'),
    ]

    operations = [
    ]
