# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-17 14:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0008_merge_20180304_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienthasboardgame',
            name='issued',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='clienthasboardgame',
            name='returned',
            field=models.DateTimeField(null=True),
        ),
    ]
