# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-14 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0009_auto_20180317_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientid',
            name='ID',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Identyfikator'),
        ),
        migrations.AlterField(
            model_name='clientid',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Aktywny'),
        ),
    ]
