# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-03 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0012_auto_20180603_1243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentalclient',
            old_name='identificationCode',
            new_name='registrationNumber',
        ),
        migrations.RenameField(
            model_name='clientid',
            old_name='ID',
            new_name='IDlabel',
        ),
        migrations.AlterField(
            model_name='clientid',
            name='IDlabel',
            field=models.CharField(max_length=12, unique=True, verbose_name='Identyfikator'),
        ),
    ]
