# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-03 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0013_auto_20180603_1256'),
    ]

    operations = [
        migrations.DeleteModel(
            name='clientid',
        ),


    ]
