# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-03 11:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0014_clientid_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDlabel', models.CharField(max_length=12, unique=True, verbose_name='Identyfikator')),
                ('active', models.BooleanField(default=True, verbose_name='Aktywny')),
                ('rentalClient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientIDs', to='circulation.RentalClient')),
            ],
        ),
    ]
