# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-05 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0015_clientid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientid',
            name='active',
        ),
        migrations.AddField(
            model_name='clientid',
            name='IDstatus',
            field=models.IntegerField(default=0, verbose_name='Status identyfikatora'),
        ),
    ]
