# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-10 10:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0017_auto_20180605_2106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardgamelending',
            old_name='client',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='customerid',
            old_name='Customer',
            new_name='customer',
        ),
    ]
