# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-10 10:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0018_auto_20180610_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerid',
            name='customer',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='CustomerIDs', to='circulation.Customer'),
            preserve_default=False,
        ),
    ]
