# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-19 19:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0019_auto_20180610_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgamelending',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lendings', to='warehouse.BoardGameContainer'),
        ),
        migrations.AlterField(
            model_name='boardgamelending',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lendings', to='circulation.Customer'),
        ),
        migrations.AlterField(
            model_name='customerid',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customerIDs', to='circulation.Customer'),
        ),
    ]
