# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-19 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0020_auto_20180619_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgamelending',
            name='issued',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
